[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#209485"

# Background color for the main content area.
backgroundColor = "#5d5f70"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#494b57"

# Color used for almost all text.
textColor = "#ffffff"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# font =